#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""build-compose.py — regenerates compose.html from lectern.html.
Run after any change to the deck: python3 build-compose.py
The deck shell (chrome + CSS + engine, slides removed) is embedded as
base64, so no <script>-escaping issues; the composer splices generated
slides into it and offers the result as a download.
NOTE: COMPOSE below is a *raw* string (protects the JS regexes). Use real
UTF-8 characters, never \\uXXXX escapes, in HTML text — a safety pass at
the bottom decodes any that slip through."""
import base64, json, re

deck = open('lectern.html', encoding='utf-8').read()
qrlib = open('vendor-qrcode.js', encoding='utf-8').read()
assert '</script' not in qrlib.lower(), 'QR lib not embeddable'


# ── carve the shell: everything except the demo slides, with markers ──
a = '<div class="slides" id="slides">'
b = '</div><!-- /slides -->'
i, j = deck.index(a), deck.index(b)
shell = deck[:i] + a + '\n<!--__SLIDES__-->\n    ' + deck[j:]
shell = shell.replace('<title>Lectern — an academic HTML slide system</title>',
                      '<title>__TITLE__</title>')
shell = shell.replace('shortTitle:"Lectern",', 'shortTitle:"__SHORT__",')
shell = shell.replace('byline:"A. Researcher · Colloquium on Reproducible Talks · 2026"',
                      'byline:"__BYLINE__"')
assert shell.count('__SLIDES__') == 1 and shell.count('__SHORT__') == 1
assert shell.count('<html lang="en">') == 1
B64 = base64.b64encode(shell.encode('utf-8')).decode('ascii')

SAMPLE_EN = """title: The Portable Talk
subtitle: Slides that travel as a single file
authors: A. Speaker (Your Institute)
venue: Group Seminar · July 2026
contact: a.speaker@example.edu
short: Portable

# Problem
Decks rot: broken links, missing fonts, lost sources.

## Why sharing slides is hard
Most decks depend on a service, an app, or a build.
- Attachments arrive broken or need an account.
- "Final_v7.pptx" is nobody's source of truth.
+ A talk should survive email, USB sticks, and 2035.
> Ask who has reopened a five-year-old deck lately.

## What we actually need
One artifact that is the slides, the source, and the archive.
- Readable everywhere a browser exists.
- Editable with any text editor.
- Printable: $1280 \\times 720$ pages with running heads.

# Approach
## One HTML file
The deck you are previewing is a single `.html` document.
- Deep links: every slide has an address like `#one-html-file`.
+ Press **P** in the preview for the presenter view.
+ Press **T** to change the theme; print stays paper.
> Demo P and T live here. Paste a screenshot to add a figure."""

SAMPLE_ZH = """title: 便携的演讲
subtitle: 一个文件，就是全部幻灯片
authors: 张三（某研究所）
venue: 组会 · 2026 年 7 月
contact: zhangsan@example.edu
short: 便携
lang: zh

# 问题
幻灯片会腐坏：链接失效、字体丢失、源文件不知去向。

## 分享幻灯片为什么难
多数幻灯片依赖某个服务、某个软件或某套构建流程。
- 附件打不开，或者需要注册账号。
- “终版_v7.pptx”不是任何人的可信来源。
+ 一场演讲应该经得起邮件、U 盘和 2035 年。
> 问问在座各位，谁最近打开过五年前的幻灯片。

# 方案
## 一个 HTML 文件
你正在预览的这份幻灯片，就是一个 `.html` 文件。
- 深链接：每一页都有地址，例如 `#一个-html-文件`。
+ 在预览中按 **P** 打开演讲者视图（备注 + 计时）。
+ 按 **T** 切换主题；打印始终是纸面配色。
> 现场演示 P 和 T。粘贴一张截图即可插入图片。"""

COMPOSE = r"""<!doctype html>
<!--
  LECTERN COMPOSE — type your talk as plain text, download a deck.
  Generated by build-compose.py from lectern.html (build __BUILD__).
  Grammar:  key: value lines first (title, subtitle, authors, venue,
            contact, short, byline, lang: zh) · # Section · ## Slide ·
            plain line = paragraph (first one is the lead) · - bullet ·
            + bullet revealed on → · two-space indent nests · > note ·
            ![name | caption] figure (paste or drop an image to insert) ·
            inline: **bold** *italic* `code` $TeX$
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Lectern Compose · 幻灯片编写器</title>
<style>
:root{--paper:#FFFFFF;--ink:#161B22;--ink-2:#5A6373;--lapis:#1E3D6B;--lapis-soft:#EDF2F8;--rubric:#A62B3A;--rule:#DCE0E6;--rule-strong:#9AA3AF;--wash:#F6F8FA;
--sans:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",system-ui,sans-serif;--mono:"JetBrains Mono",ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
*{box-sizing:border-box}
html,body{margin:0;height:100%}
body{display:flex;flex-direction:column;background:var(--wash);font-family:var(--sans);color:var(--ink)}
header{display:flex;align-items:center;gap:14px;padding:12px 18px;background:var(--paper);border-bottom:1px solid var(--rule)}
header h1{font:600 15px var(--mono);letter-spacing:.12em;text-transform:uppercase;color:var(--lapis);margin:0 8px 0 0;white-space:nowrap}
header .hint{font-size:12.5px;color:var(--ink-2)}
#status{margin-left:auto;font:500 12.5px var(--mono);color:var(--ink-2);white-space:nowrap}
#status.bad{color:var(--rubric)}
button,label.btn{background:var(--lapis);color:#fff;border:0;border-radius:7px;padding:8px 14px;font:600 13px var(--sans);cursor:pointer;white-space:nowrap}
label.btn,#lang,#exp{background:var(--paper);color:var(--ink);border:1px solid var(--rule-strong)}
.opt{display:flex;gap:8px;align-items:center;font:500 12px var(--sans);color:var(--ink-2);white-space:nowrap}
.opt select{border:1px solid var(--rule);border-radius:6px;padding:4px 6px;font:500 12px var(--sans);color:var(--ink);background:var(--paper)}
#warn .chip[data-act="arch"]{border-color:var(--lapis)}
input[type=file]{display:none}
#fname{border:1px solid var(--rule);border-radius:7px;padding:7px 10px;font:500 13px var(--mono);width:190px;color:var(--ink)}
main{flex:1;display:grid;grid-template-columns:minmax(380px,44%) 1fr;gap:14px;padding:14px;min-height:0}
.pane{background:var(--paper);border:1px solid var(--rule);border-radius:10px;display:flex;flex-direction:column;min-height:0;overflow:hidden}
.pane h2{font:600 11px var(--sans);letter-spacing:.14em;text-transform:uppercase;color:var(--ink-2);margin:0;padding:10px 14px;border-bottom:1px solid var(--rule)}
#outline{flex:1;border:0;resize:none;padding:14px 16px;font:400 14px/1.6 var(--mono);color:var(--ink);outline:none;background:var(--paper)}
#outline.drop{outline:2px dashed var(--lapis);outline-offset:-6px}
#pv{flex:1;border:0;width:100%;background:var(--wash)}
#warn{padding:8px 14px;border-top:1px solid var(--rule);font:500 12.5px var(--mono);color:var(--ink-2);max-height:96px;overflow:auto}
#warn .bad{color:var(--rubric)}
#warn .info{color:var(--ink-2)}
#warn .chip{margin-left:8px;padding:2px 9px;border-radius:6px;border:1px solid var(--rule-strong);background:var(--paper);color:var(--ink);font:600 11px var(--sans);cursor:pointer;vertical-align:1px}
.cheat{padding:8px 14px;border-top:1px solid var(--rule);font:400 12px/1.7 var(--mono);color:var(--ink-2)}
.cheat code{background:var(--wash);border:1px solid var(--rule);border-radius:4px;padding:0 5px}
@media (max-width:900px){main{grid-template-columns:1fr;grid-template-rows:1fr 1fr}}
</style>
</head>
<body>
<header>
  <h1>Lectern · Compose</h1>
  <span class="hint" id="hint"></span>
  <span id="status"></span>
  <span class="opt"><label><input type="checkbox" id="embM"> <span id="embMT"></span></label>
  <select id="thSel" aria-label="Theme"><option value="">Paper</option><option value="slate">Slate</option><option value="sepia">Sepia</option></select></span>
  <input id="fname" value="my-talk.html" aria-label="File name">
  <button id="lang" title="切换语言 / switch language"></button>
  <button id="exp" class="sec"></button>
  <label class="btn"><span id="impT"></span><input type="file" id="imp" accept=".html,.txt"></label>
  <button id="dl"></button>
</header>
<main>
  <section class="pane">
    <h2 id="oh2"></h2>
    <textarea id="outline" spellcheck="false" aria-label="Talk outline"></textarea>
    <div class="cheat" id="cheat"></div>
  </section>
  <section class="pane">
    <h2 id="ph2"></h2>
    <iframe id="pv" title="Deck preview"></iframe>
    <div id="warn"></div>
  </section>
</main>

<script>
__QRLIB__
</script>
<script>
(function(){
'use strict';
var SHELL_B64='__SHELL__';
var SAMPLE=__SAMPLE__;
function b64d(s){return decodeURIComponent(escape(atob(s)));}
function b64e(s){return btoa(unescape(encodeURIComponent(s)));}
var SHELL=b64d(SHELL_B64);
var $=function(q){return document.querySelector(q);};

/* ── i18n ─────────────────────────────────────────────────────── */
var STR={
en:{hint:'Type your talk on the left. The deck builds itself on the right.',
    oh2:'Outline — what to say, slide by slide',
    ph2:'Live preview — click it, then use the deck keys (← → O P T …)',
    dl:'Download deck',imp:'Import deck',lang:'中文',
    cheat:'<code># Section</code> · <code>## Slide title</code> · plain line = paragraph · <code>- bullet</code> · <code>+ step (→)</code> · <code>++ dim step</code> · <code>$$eq$$</code> · two-space indent nests · <code>&gt; note</code> · paste / drop an image · <code>**bold**</code> <code>*italic*</code> <code>`code`</code> <code>$TeX$</code> · <code>::compact</code> · <code>|</code> alone = columns · <code>|a|b|</code> table (+<code>|=</code> caption) · <code>[@key]</code> with <code>refs:</code> · <code>!video[url]</code> · <code>## T @4m</code>+<code>time: 25m</code> · <code>::fx slide</code> · <code># … ::backup</code> appendix · <code>link:</code> → QR · <code>theme:</code> · <code>lang: zh</code>',
    fits:'fits ✓',ovfN:' overflow',pages:' slides · ',
    warnFit:'Every slide fits the 1280×720 canvas.',
    warnRow:function(r){return '⚠ slide '+r.slide+' ('+r.id+') is '+r.overflow+' too tall — trim or split it';},
    noOutline:'No Lectern outline found in that file — it may predate Compose or be hand-edited.',
    cap:'caption for this figure',missing:'missing image: ',
    split:'Split',compact:'Compact',extern:'external asset — no longer self-contained: ',sizeBig:' — large for email; consider trimming',
    archive:'Archive',archFail:'archive failed (CORS/network): ',
    bkTrail:'a normal # section follows a ::backup one — appendix sections must come last (everything after the first stays appendix).',
    exp:'Export outline',embed:'Embed math (+≈400 KB, offline)',embWork:'embedding math…',
    embFail:'math embed failed — CDN lines kept: ',thm:['Paper','Slate','Sepia']},
zh:{hint:'左侧输入讲稿，右侧自动生成幻灯片。',
    oh2:'大纲 — 每一页要讲的内容',
    ph2:'实时预览 — 点击后即可使用快捷键（← → O P T …）',
    dl:'下载幻灯片',imp:'导入幻灯片',lang:'EN',
    cheat:'<code># 章节</code> · <code>## 幻灯片标题</code> · 普通行 = 段落 · <code>- 要点</code> · <code>+ 分步显示 (→)</code> · <code>++ 变暗分步</code> · <code>$$公式$$</code> · 行首两个空格 = 子要点 · <code>&gt; 演讲备注</code> · 直接粘贴 / 拖入图片 · <code>**粗体**</code> <code>*斜体*</code> <code>`代码`</code> <code>$公式$</code> · <code>::compact</code> · 单独一行 <code>|</code> = 分栏 · <code>|a|b|</code> 表格（<code>|=</code> 表题）· <code>[@key]</code> 配 <code>refs:</code> · <code>!video[url]</code> · <code>## 标题 @4m</code>+<code>time: 25m</code> · <code>::fx slide</code> · <code># … ::backup</code> 附录 · <code>link:</code> → 二维码 · <code>theme:</code> · <code>lang: zh</code>',
    fits:'全部适配 ✓',ovfN:' 页超高',pages:' 页 · ',
    warnFit:'每一页都在 1280×720 画布之内。',
    warnRow:function(r){return '⚠ 第 '+r.slide+' 页（'+r.id+'）超出 '+r.overflow+' — 请精简或拆分';},
    noOutline:'未在该文件中找到 Compose 大纲 — 它可能不是由 Compose 生成，或已被手工改动。',
    cap:'在此填写图注',missing:'缺少图片：',
    split:'拆分',compact:'紧凑',extern:'外部资源 — 文件不再自包含：',sizeBig:' — 文件较大，建议压缩后再邮件发送',
    archive:'归档',archFail:'归档失败（跨域/网络）：',
    bkTrail:'::backup 章节之后又出现了普通章节 — 附录必须放在最后（其后的内容都按附录处理）。',
    exp:'导出大纲',embed:'内嵌数学渲染器（+约 400 KB，完全离线）',embWork:'正在内嵌数学…',
    embFail:'数学内嵌失败 — 已保留 CDN 引用：',thm:['纸面','石板','棕褐']}
};
var DECKSTR={
en:{contents:'Contents',agenda:'Agenda',qa:'Questions &amp; discussion',fig:'Figure',tbl:'Table',refs:'References',
    src:'slides — this file is the source: view, copy, edit, share',
    pages:function(n){return n+' slide'+(n>1?'s':'');}},
zh:{contents:'目录',agenda:'议程',qa:'问答与讨论',fig:'图',tbl:'表',refs:'参考文献',
    src:'幻灯片 — 本文件即源码：查看、复制、编辑、分享',
    pages:function(n){return n+' 页';}}
};
var LANG='en';
try{LANG=localStorage.getItem('lectern-compose-lang')||'en';}catch(e){}
if(!STR[LANG])LANG='en';
function setLang(l){
  if(!STR[l])return;
  var untouched=$('#outline').value.trim()===SAMPLE[LANG].trim();
  LANG=l;
  try{localStorage.setItem('lectern-compose-lang',l);}catch(e){}
  var s=STR[l];
  $('#hint').textContent=s.hint;$('#oh2').textContent=s.oh2;$('#ph2').textContent=s.ph2;
  $('#dl').textContent=s.dl;$('#impT').textContent=s.imp;$('#lang').textContent=s.lang;
  $('#exp').textContent=s.exp;$('#embMT').textContent=s.embed;
  Array.prototype.forEach.call($('#thSel').options,function(o,k){o.textContent=s.thm[k];});
  $('#cheat').innerHTML=s.cheat;
  document.documentElement.lang=(l==='zh')?'zh-CN':'en';
  if(untouched){$('#outline').value=SAMPLE[l];}
  refresh();
}

/* ── text helpers ─────────────────────────────────────────────── */
function escT(t){return String(t).replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
function fmt(x){
  x=escT(x);
  x=x.replace(/\$([^$]+)\$/g,'<span class="math">$1</span>');
  x=x.replace(/`([^`]+)`/g,'<code>$1</code>');
  x=x.replace(/\*\*([^*]+)\*\*/g,'<b>$1</b>');
  x=x.replace(/\*([^*]+)\*/g,'<i>$1</i>');
  x=x.replace(/\[@([\w.\-]+)\]/g,function(_,k){
    if(REFS[k]){
      if(!(k in CITE.n)){CITE.n[k]=CITE.order.length+1;CITE.order.push(k);}
      return '<sup class="cite">['+CITE.n[k]+']</sup>';
    }
    return '<sup class="cite cite--bad">[?'+k+']</sup>';
  });
  return x;
}
function qrSvg(u){
  try{
    var q=window.qrcode(0,'M');q.addData(String(u));q.make();
    var n=q.getModuleCount(),d='';
    for(var y=0;y<n;y++)for(var x=0;x<n;x++)if(q.isDark(y,x))d+='M'+x+' '+y+'h1v1h-1z';
    return '<svg viewBox="0 0 '+n+' '+n+'" width="150" height="150" shape-rendering="crispEdges" role="img" aria-label="QR code"><path d="'+d+'" fill="currentColor"/></svg>';
  }catch(e){return '';}
}
var RESERVED={title:1,agenda:1,end:1,ink:1,toc:1,find:1,toast:1,ovf:1,veil:1,stage:1,deck:1,slides:1};
function slug(t,used){
  var s=String(t).toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g,'-').replace(/^-+|-+$/g,'')||'slide';
  var v=s,k=2;
  while(used[v]||RESERVED[v]){v=s+'-'+(k++);}
  used[v]=1;return v;
}

/* ── outline grammar ──────────────────────────────────────────── */
function parseOutline(txt){
  var meta={title:'Untitled Talk',subtitle:'',authors:'',venue:'',contact:'',short:'',byline:'',lang:'',time:'',refs:{},link:'',theme:''};
  var refsMode=false;
  var secs=[],curSec=null,curSl=null,started=false;
  String(txt).split(/\r?\n/).forEach(function(line,LN){
    var l=line.replace(/\s+$/,''),m;
    if(!l.trim())return;
    if(refsMode){
      if(m=l.match(/^\s+([\w.\-]+)\s*:\s*(.+)/)){meta.refs[m[1]]=m[2].trim();return;}
      refsMode=false;
    }
    if(m=l.match(/^##\s+(.+)/)){
      started=true;
      if(!curSec){curSec={t:'',sub:[],slides:[]};secs.push(curSec);}
      var tt=m[1].trim(),tmm=tt.match(/\s@([\d.]+)m$/),mn=0;
      if(tmm){mn=+tmm[1];tt=tt.slice(0,tmm.index).replace(/\s+$/,'');}
      curSl={t:tt,body:[],notes:[],line:LN,dir:{},min:mn};curSec.slides.push(curSl);return;
    }
    if(m=l.match(/^#\s+(.+)/)){
      started=true;
      var st1=m[1].trim(),bk1=false;
      if(/\s::backup\s*$/i.test(st1)){bk1=true;st1=st1.replace(/\s*::backup\s*$/i,'');}
      curSec={t:st1,sub:[],slides:[],line:LN,backup:bk1};secs.push(curSec);curSl=null;return;
    }
    if(!started){
      if(/^refs:\s*$/i.test(l)){refsMode=true;return;}
      if(m=l.match(/^([A-Za-z]+)\s*:\s*(.+)/)){
        var k=m[1].toLowerCase();
        if(meta.hasOwnProperty(k)){meta[k]=m[2].trim();return;}
      }
      if(!meta.subtitle)meta.subtitle=l.trim();
      return;
    }
    if(m=l.match(/^>\s?(.*)/)){if(curSl)curSl.notes.push(m[1]);return;}
    if(curSl){
      if(m=l.match(/^::(\w+)(?:\s+(.+))?$/)){curSl.dir[m[1]]=m[2]||true;return;}
      if(m=l.match(/^\$\$(.+)\$\$\s*$/)){curSl.body.push({t:'eq',x:m[1].trim()});return;}
      if(m=l.match(/^(\s*)\+\+\s+(.+)/)){curSl.body.push({t:'li',frag:true,dim:true,d:m[1].length>=2?1:0,x:m[2]});return;}
      if(/^\|\s*$/.test(l)){curSl.body.push({t:'br'});return;}
      if(/^\|/.test(l)){
        var last=curSl.body[curSl.body.length-1];
        if(m=l.match(/^\|=\s*(.+)/)){if(last&&last.t==='tbl')last.cap=m[1].trim();return;}
        var cells=l.replace(/^\|/,'').replace(/\|\s*$/,'').split('|').map(function(c){return c.trim();});
        var isDiv=cells.length>0&&cells.every(function(c){return /^:?-{3,}:?$/.test(c);});
        if(!(last&&last.t==='tbl')){last={t:'tbl',rows:[],align:null,head:false,cap:''};curSl.body.push(last);}
        if(isDiv){last.head=last.rows.length===1;last.align=cells.map(function(c){return /-:$/.test(c)?'r':'l';});}
        else last.rows.push(cells);
        return;
      }
      if(m=l.match(/^!video\[([^\]|]+?)(?:\s*\|\s*(.+?))?\]\s*$/)){
        curSl.body.push({t:'vid',src:m[1].trim(),cap:(m[2]||'').trim()});return;
      }
      if(m=l.match(/^!\[([^\]|]+?)(?:\s*\|\s*([^\]|]*?))?(?:\s*\|\s*([A-Za-z]+))?\]\s*$/)){
        curSl.body.push({t:'img',name:m[1].trim(),cap:(m[2]||'').trim(),place:(m[3]||'').toLowerCase()});return;
      }
      if(m=l.match(/^(\s*)([-+*])\s+(.+)/)){
        curSl.body.push({t:'li',frag:m[2]==='+',d:m[1].length>=2?1:0,x:m[3]});return;
      }
      curSl.body.push({t:'p',x:l.trim()});return;
    }
    if(curSec)curSec.sub.push(l.trim());
  });
  return{meta:meta,secs:secs};
}

/* ── pasted / dropped pictures ────────────────────────────────── */
var ASSETS={},imgN=0,MAP=[],LINTS=[],REFS={},CITE={n:{},order:[]},FIGN=0,TBLN=0,DSTR=DECKSTR.en;
var pendingMsgs=[];
var doFetch=function(u){return (typeof fetch==='function')?fetch(u):Promise.reject(new Error('fetch unavailable'));};
function renderImg(it){
  var ext=/^https?:\/\//.test(it.name);
  var src=ext?it.name:ASSETS[it.name];
  if(!src)return '<p class="lead" style="color:var(--rubric)">['+STR[LANG].missing+escT(it.name)+']</p>';
  if(ext)LINTS.push({kind:'img',url:it.name,msg:STR[LANG].extern+it.name});
  FIGN++;
  var cap=it.cap?'<figcaption><b>'+DSTR.fig+' '+FIGN+'</b> — '+fmt(it.cap)+'</figcaption>':'';
  var nm=ext?'':' data-name="'+escT(it.name)+'"';
  var box='border:1px solid var(--rule);border-radius:6px;display:block';
  src=escT(src);
  if(it.place==='fill'){
    return '<figure class="fig" style="flex:1;min-height:0;display:flex;flex-direction:column;margin:0">'
      +'<img'+nm+' src="'+src+'" alt="'+escT(it.cap||it.name)+'" style="flex:1;min-height:0;width:100%;object-fit:contain;'+box+'">'+cap+'</figure>';
  }
  return '<figure class="fig"><img'+nm+' src="'+src+'" alt="'+escT(it.cap||it.name)+'"'
    +' style="max-width:100%;max-height:420px;margin:0 auto;'+box+'">'+cap+'</figure>';
}
function renderVid(it){
  LINTS.push({kind:'vid',url:it.src,msg:STR[LANG].extern+it.src});
  return '<figure class="frame" style="--ratio:16/9"><figcaption class="frame__bar"><i class="frame__dot"></i>'
    +escT(it.cap||it.src)+'</figcaption><video data-src="'+escT(it.src)+'" controls playsinline preload="none"></video></figure>';
}
function renderTbl(it){
  TBLN++;
  var al=it.align||[];
  function row(cells,tag){
    return '<tr>'+cells.map(function(c,ci){
      return '<'+tag+(al[ci]==='r'?' class="num"':'')+'>'+fmt(c)+'</'+tag+'>';
    }).join('')+'</tr>';
  }
  var rows=it.rows.slice(),h='';
  if(it.head&&rows.length)h='<thead>'+row(rows.shift(),'th')+'</thead>';
  return '<table class="tbl">'
    +(it.cap?'<caption><b>'+DSTR.tbl+' '+TBLN+'</b> — '+fmt(it.cap)+'</caption>':'')
    +h+'<tbody>'+rows.map(function(r2){return row(r2,'td');}).join('')+'</tbody></table>';
}
function insertAtCursor(el,text){
  var s=el.selectionStart||0,e=el.selectionEnd||0,v=el.value;
  el.value=v.slice(0,s)+text+v.slice(e);
  el.selectionStart=el.selectionEnd=s+text.length;
  el.focus();
}
function nextName(){
  var name='pic-'+(++imgN);
  while(ASSETS[name])name='pic-'+(++imgN);
  return name;
}
function processBlob(blob,cb){
  if(!blob||!/^image\//.test(blob.type||'')){cb(null);return;}
  var rd=new FileReader();
  rd.onerror=function(){cb(null);};
  rd.onload=function(){
    var raw=rd.result,done=false;
    function fin(u){if(done)return;done=true;cb(u);}
    var img=new Image();
    var tmo=setTimeout(function(){fin(raw);},300); /* jsdom / no decoder: keep raw */
    img.onload=function(){
      clearTimeout(tmo);
      var url=raw;
      try{
        var MAX=1600,k=Math.min(1,MAX/img.width);
        var c=document.createElement('canvas');
        c.width=Math.max(1,Math.round(img.width*k));
        c.height=Math.max(1,Math.round(img.height*k));
        var x=c.getContext('2d');
        if(x){
          x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);
          x.drawImage(img,0,0,c.width,c.height);
          var jp=c.toDataURL('image/jpeg',.85);
          if(jp.length<url.length)url=jp;
        }
      }catch(e){}
      fin(url);
    };
    img.onerror=function(){clearTimeout(tmo);fin(raw);};
    img.src=raw;
  };
  rd.readAsDataURL(blob);
}
function addImage(file){
  processBlob(file,function(url){
    if(!url)return;
    var name=nextName();
    ASSETS[name]=url;
    insertAtCursor(ta,'\n!['+name+' | '+STR[LANG].cap+']\n');
    refresh();
  });
}
/* archive (H3): pull external images into the file, one honest result per URL */
function archiveAll(){
  var urls=[];
  LINTS.forEach(function(x){if(x.kind==='img'&&urls.indexOf(x.url)<0)urls.push(x.url);});
  var text=ta.value;
  return Promise.all(urls.map(function(u){
    return doFetch(u).then(function(r){
      if(!r.ok)throw new Error('HTTP '+r.status);
      return r.blob();
    }).then(function(b){
      return new Promise(function(res,rej){
        processBlob(b,function(url){url?res(url):rej(new Error('not an image'));});
      });
    }).then(function(dataUrl){
      var name=nextName();
      ASSETS[name]=dataUrl;
      text=text.split('!['+u).join('!['+name);
      return{u:u,ok:true};
    }).catch(function(e){
      pendingMsgs.push(STR[LANG].archFail+u+' ('+String(e&&e.message||e)+')');
      return{u:u,ok:false};
    });
  })).then(function(rs){
    if(text!==ta.value)applyOutline(text);else refresh();
    return rs;
  });
}

/* ── deck assembly ────────────────────────────────────────────── */
function seq(body,st){
  var out=[],buf=[];
  function flush(){
    if(!buf.length)return;
    var h='<ul>',open=false;
    buf.forEach(function(it){
      var li='<li'+(it.frag?' class="frag'+(it.dim?' frag--dim':'')+'"':'')+'>'+fmt(it.x)+'</li>';
      if(it.d===1){
        if(!open){h=h.replace(/<\/li>$/,'');h+='<ul>';open=true;}
        h+=li;
      }else{
        if(open){h+='</ul></li>';open=false;}
        h+=li;
      }
    });
    if(open)h+='</ul></li>';
    out.push(h+'</ul>');buf=[];
  }
  body.forEach(function(it){
    if(it.t==='li'){buf.push(it);return;}
    flush();
    if(it.t==='img'){out.push(renderImg(it));return;}
    if(it.t==='vid'){out.push(renderVid(it));return;}
    if(it.t==='tbl'){out.push(renderTbl(it));return;}
    if(it.t==='eq'){out.push('<div class="math math--eq">'+escT(it.x)+'</div>');return;}
    if(it.t==='br')return;
    out.push('<p'+(st.sawP?'':' class="lead"')+'>'+fmt(it.x)+'</p>');st.sawP=true;
  });
  flush();
  return out.join('\n        ');
}
function renderBody(body){
  var cut=-1;
  body.forEach(function(it,k){if(cut<0&&it.t==='br')cut=k;});
  if(cut<0)return seq(body,{sawP:false});
  var L=body.slice(0,cut),R=body.slice(cut+1);
  var st={sawP:false};
  function lone(a){return a.length===1&&a[0].t==='img'&&a[0].place==='fill';}
  function cell(a){
    var f=lone(a);
    return '<div'+(f?' style="align-self:stretch;display:flex;flex-direction:column;min-height:0"':'')+'>'+seq(a,st)+'</div>';
  }
  return '<div class="cols">'+cell(L)+cell(R)+'</div>';
}
function buildDeck(txt){
  var o=parseOutline(txt),m=o.meta,used={},nn=0,html=[],ix=0;
  MAP=[];
  function mp(id,line){MAP.push({i:ix++,id:id,start:(line===undefined?0:line),src:line!==undefined});}
  var dl=/^(zh|cn|中文)/i.test(m.lang)?'zh':(m.lang?'en':(LANG==='zh'?'zh':'en'));
  var D=DECKSTR[dl];
  DSTR=D;REFS=m.refs||{};LINTS=[];CITE={n:{},order:[]};FIGN=0;TBLN=0;
  /* pacing (G7): explicit @Xm budgets keep theirs; time: spreads the rest */
  var totalM=parseFloat((String(m.time).match(/[\d.]+/)||[0])[0])||0;
  var flat=[];o.secs.forEach(function(sc){if(sc.backup)return;sc.slides.forEach(function(sl){flat.push(sl);});});
  var expM=0,unb=0,seenBk=false,bkLinted=false;
  flat.forEach(function(sl){if(sl.min)expM+=sl.min;else unb++;});
  var share=(totalM>expM&&unb)?(totalM-expM)/unb:0;
  flat.forEach(function(sl){sl._min=sl.min||share;});
  mp('title',0);
  html.push('<section class="slide slide--title" id="title">',
    '<svg class="logo" aria-hidden="true"><use href="#logo"/></svg>',
    '<h1>'+fmt(m.title)+'</h1>',
    m.subtitle?'<p class="subtitle">'+fmt(m.subtitle)+'</p>':'',
    m.authors?'<p class="authors">'+fmt(m.authors)+'</p>':'',
    m.venue?'<p class="venue">'+fmt(m.venue)+'</p>':'',
    '</section>');
  var named=o.secs.filter(function(s){return s.t;});
  if(named.length>=2){
    mp('agenda');
    html.push('<section class="slide" id="agenda" data-agenda>',
      '<header><p class="kicker">'+D.contents+'</p><h2>'+D.agenda+'</h2></header>',
      '<nav class="agenda" aria-label="Sections"></nav></section>');
  }
  o.secs.forEach(function(sec){
    if(sec.t){
      if(sec.backup)seenBk=true;
      else if(seenBk&&!bkLinted){bkLinted=true;LINTS.push({kind:'lint',msg:STR[LANG].bkTrail});}
      var sid=slug(sec.t,used);
      mp(sid,sec.line);
      if(!sec.backup)nn++;
      html.push('<section class="slide slide--section" id="'+sid+'" data-section="'+escT(sec.t)+'"'
          +(sec.backup?' data-backup':' data-sn="'+nn+'"')+'>',
        '<p class="sec__no">§ '+(sec.backup?'A':String(nn).padStart(2,'0'))+'</p>',
        '<h2>'+fmt(sec.t)+'</h2>',
        sec.sub.length?'<p class="sec__sub">'+fmt(sec.sub.join(' '))+'</p>':'',
        '</section>');
    }
    sec.slides.forEach(function(sl){
      var lid=slug(sl.t,used);
      mp(lid,sl.line);
      html.push('<section class="slide'+(sl.dir&&sl.dir.compact?' h-compact':'')+'" id="'+lid+'"'
        +(sl.dir&&typeof sl.dir.fx==='string'?' data-fx="'+escT(sl.dir.fx)+'"':'')
        +(sl._min?' data-min="'+(+sl._min.toFixed(2))+'"':'')+'>',
        '<header><p class="kicker">'+fmt(sec.t||m.short||'Talk')+'</p><h2>'+fmt(sl.t)+'</h2></header>',
        renderBody(sl.body),
        sl.notes.length?'<aside class="notes">'+fmt(sl.notes.join(' '))+'</aside>':'',
        '</section>');
    });
  });
  var wroteRefs=('references' in used)||('参考文献' in used);
  if(CITE.order.length&&!wroteRefs){
    mp('references');
    html.push('<section class="slide" id="references">',
      '<header><p class="kicker">'+D.contents+'</p><h2>'+D.refs+'</h2></header>',
      '<ol class="refs"'+(CITE.order.length>6?' style="columns:2;column-gap:52px"':'')+'>'
        +CITE.order.map(function(k){return '<li>'+fmt(REFS[k])+'</li>';}).join('')+'</ol>',
      '</section>');
  }
  mp('end');
  html.push('<section class="slide slide--end" id="end">',
    '<svg class="logo" aria-hidden="true"><use href="#logo"/></svg>',
    '<h2>'+D.qa+'</h2>',
    m.link?('<div class="qr" style="margin:20px auto 6px;line-height:0;color:var(--ink)">'+qrSvg(m.link)+'</div>'
      +'<p class="src" style="margin:0 0 10px">'+escT(m.link)+'</p>'):'',
    (m.contact||m.authors)?'<p class="contact"><b>'+fmt(m.contact||m.authors)+'</b></p>':'',
    '<p class="src">'+D.src+'</p>',
    '</section>');
  /* the engine builds agenda counts as "n slides"; localise afterwards */
  var short=(m.short||m.title).slice(0,24);
  var byline=m.byline||[m.authors,m.venue].filter(Boolean).join(' · ')||short;
  function jq(v){var BS=String.fromCharCode(92);return String(v).split(BS).join(BS+BS).split('"').join(BS+'"').split('<').join(BS+'u003C');}
  function put(hay,mark,val){return hay.split(mark).join(val);}
  var out=put(SHELL,'<!--__SLIDES__-->',html.filter(Boolean).join('\n      '));
  out=put(out,'__TITLE__',escT(m.title));
  out=put(out,'__SHORT__',jq(short));
  out=put(out,'__BYLINE__',jq(byline));
  if(dl==='zh'){
    out=put(out,'<html lang="en">','<html lang="zh-CN">');
    out=put(out,"count+' slide'+(count>1?'s':'')","count+' 页'");
  }
  var thv=/^(slate|sepia)$/i.exec(String(m.theme).trim());
  if(thv){
    var htag=dl==='zh'?'<html lang="zh-CN">':'<html lang="en">';
    out=put(out,htag,htag.replace('<html ','<html data-theme="'+thv[1].toLowerCase()+'" '));
  }
  var k=out.lastIndexOf('</body>');
  return out.slice(0,k)+'<!--lectern-outline:v1:'+b64e(txt)+'-->\n'+out.slice(k);
}
function extractOutline(deckHtml){
  var m=String(deckHtml).match(/lectern-outline:(?:v(\d+):)?([A-Za-z0-9+\/=]+)/);
  return m?b64d(m[2]):null;
}
function extractAssets(deckHtml){
  var out={},re=/<img data-name="([^"]+)" src="(data:[^"]+)"/g,m;
  while(m=re.exec(String(deckHtml)))out[m[1]]=m[2];
  return out;
}

/* ── outline ⇄ preview sync (G1) ─────────────────────────────── */
function byId(id){for(var k=0;k<MAP.length;k++)if(MAP[k].id===id)return MAP[k];return null;}
function caretIndex(ln){
  var hit=null;
  MAP.forEach(function(e){if(e.src&&e.start<=ln)hit=e;});
  return hit||MAP[0]||null;
}
function blockBounds(id){
  var e=byId(id);if(!e||!e.src)return null;
  var end=1e9;
  MAP.forEach(function(o){if(o.src&&o.start>e.start&&o.start<end)end=o.start;});
  return{start:e.start,end:end};
}

/* ── one-click overflow fixes (G2): visible, undoable text edits ── */
function applyOutline(newText){
  var ok=false;
  try{
    ta.focus();ta.setSelectionRange(0,ta.value.length);
    ok=document.execCommand&&document.execCommand('insertText',false,newText);
  }catch(e){ok=false;}
  if(!ok||ta.value!==newText)ta.value=newText;
  clearTimeout(tId);refresh();
}
function fixSlide(id,act){
  buildDeck(ta.value);                       /* refresh MAP for current text */
  var b=blockBounds(String(id).replace(/^#/,''));
  if(!b)return;
  var lines=ta.value.split('\n');
  var end=Math.min(b.end,lines.length)-1;
  if(act==='compact'){
    for(var q=b.start+1;q<=end;q++)if(/^::compact\s*$/.test(lines[q]))return;
    var pos=b.start+1;
    while(pos<=end&&/^::/.test(lines[pos]))pos++;
    lines.splice(pos,0,'::compact');
    applyOutline(lines.join('\n'));
    return;
  }
  if(act==='split'){
    var content=[];
    for(var q2=b.start+1;q2<=end;q2++){
      var t2=lines[q2];
      if(t2.trim()&&!/^>/.test(t2)&&!/^::/.test(t2))content.push(q2);
    }
    if(content.length<2)return;
    var k2=Math.ceil(content.length/2);
    var moved=content.slice(content.length-k2);
    var movedText=moved.map(function(q3){return lines[q3];});
    var dl=/^(zh|cn|中文)/i.test(parseOutline(ta.value).meta.lang)?'zh':(LANG==='zh'?'zh':'en');
    var suf=dl==='zh'?'（续）':' — cont.';
    var title=lines[b.start].replace(/^##\s+/,'');
    if(title.slice(-suf.length)!==suf)title=title+suf;
    var kept=lines.filter(function(_,q4){return moved.indexOf(q4)<0;});
    var insertAt=end+1-moved.filter(function(q5){return q5<=end;}).length;
    kept.splice(insertAt,0,'','## '+title,movedText.join('\n'));
    applyOutline(kept.join('\n'));
  }
}

/* ── embed math renderer (H4): CDN pair → inline css+fonts+js ── */
function _embedMath(deck){
  var mL=deck.match(/<link rel="stylesheet" href="(https:[^"]*katex[^"]*\.css)">/);
  var mS=deck.match(/<script defer src="(https:[^"]*katex[^"]*\.js)"><\/script>/);
  if(!mL||!mS)return Promise.resolve({deck:deck,ok:false,why:'no CDN lines found'});
  var cssU=mL[1],jsU=mS[1],base=cssU.replace(/[^\/]+$/,'');
  function txt(u){return doFetch(u).then(function(r){if(!r.ok)throw new Error(u);return r.text();});}
  function bin(u){return doFetch(u).then(function(r){if(!r.ok)throw new Error(u);return r.arrayBuffer();});}
  return Promise.all([txt(cssU),txt(jsU)]).then(function(a){
    var css=a[0],js=a[1];
    if(/<\/script/i.test(js))throw new Error('renderer source is not embeddable');
    var fonts=[];
    css.replace(/url\((fonts\/[^)]+?\.woff2)\)/g,function(_,f){if(fonts.indexOf(f)<0)fonts.push(f);return _;});
    return Promise.all(fonts.map(function(f){return bin(base+f);})).then(function(bufs){
      bufs.forEach(function(buf,i){
        var b=new Uint8Array(buf),s2='';
        for(var k=0;k<b.length;k++)s2+=String.fromCharCode(b[k]);
        css=css.split('url('+fonts[i]+')').join('url(data:font/woff2;base64,'+btoa(s2)+')');
      });
      var out2=deck.replace(mL[0],'<style>'+css+'</style>')
                   .replace(mS[0],'<script>'+js+'<\/script>');
      return{deck:out2,ok:true,fonts:fonts.length};
    });
  }).catch(function(e){return{deck:deck,ok:false,why:String(e&&e.message||e)};});
}

/* ── UI wiring ────────────────────────────────────────────────── */
var ta=$('#outline'),pv=$('#pv'),warn=$('#warn'),status=$('#status'),tId=0,cId=0,lastPvId='title';
function caretLine(){return String(ta.value).slice(0,ta.selectionStart||0).split('\n').length-1;}
function syncFromCaret(){
  var hit=caretIndex(caretLine());
  if(!hit||hit.id===lastPvId)return;
  try{pv.contentWindow.Lectern.go(hit.i+1);lastPvId=hit.id;}catch(e){}
}
function refresh(){
  var deck=buildDeck(ta.value);
  var lints=LINTS.slice();
  var pend=pendingMsgs.splice(0);
  try{$('#thSel').value=(/^(slate|sepia)$/i.exec(String(parseOutline(ta.value).meta.theme).trim())||['',''])[1].toLowerCase();}catch(e){}
  var bytes=new Blob([deck]).size;
  var big=bytes>8*1048576;
  var sz=bytes>1048576?(bytes/1048576).toFixed(1)+' MB':Math.round(bytes/1024)+' KB';
  pv.onload=function(){
    setTimeout(function(){
      var s=STR[LANG];
      try{
        var L=pv.contentWindow.Lectern;
        /* keep place across rebuilds; caret wins while typing */
        var target=(document.activeElement===ta)?caretIndex(caretLine()):byId(lastPvId);
        if(target){try{L.go(target.i+1);lastPvId=target.id;}catch(e0){}}
        /* preview navigation scrolls the outline (never the caret) */
        L.on('slide',function(ev){
          lastPvId=ev.id;
          if(document.activeElement===ta)return;
          var e2=byId(ev.id);
          if(e2&&e2.src){
            var lh=parseFloat(getComputedStyle(ta).lineHeight)||22.4;
            ta.scrollTop=Math.max(0,(e2.start-2)*lh);
          }
        });
        var st=L.state(),bad=L.check();
        status.textContent=st.tot+s.pages+(bad.length?bad.length+s.ovfN:s.fits)+' · '+sz;
        status.className=(bad.length||big)?'bad':'';
        var hasImg=lints.some(function(x){return x.kind==='img';});
        var info=pend.map(function(x){return '<div class="bad">'+escT(x)+'</div>';}).join('')
          +lints.map(function(x){return '<div class="info">'+escT(x.msg)+'</div>';}).join('')
          +(hasImg?'<div class="info"><button class="chip" data-act="arch">'+escT(s.archive)+'</button></div>':'')
          +(big?'<div class="bad">'+escT(sz+s.sizeBig)+'</div>':'');
        warn.innerHTML=info+(bad.length
          ?bad.map(function(r){
              var rid=escT(String(r.id).replace(/^#/,''));
              return '<div class="bad">'+escT(s.warnRow(r))
                +' <button class="chip" data-id="'+rid+'" data-act="split">'+escT(s.split)+'</button>'
                +'<button class="chip" data-id="'+rid+'" data-act="compact">'+escT(s.compact)+'</button></div>';
            }).join('')
          :escT(s.warnFit));
      }catch(e){status.textContent='';warn.textContent='';}
    },350);
  };
  pv.srcdoc=deck;
}
warn.addEventListener('click',function(e){
  var b=e.target.closest&&e.target.closest('button.chip');
  if(!b)return;
  if(b.getAttribute('data-act')==='arch'){archiveAll();return;}
  fixSlide(b.getAttribute('data-id'),b.getAttribute('data-act'));
});
ta.addEventListener('keyup',function(){clearTimeout(cId);cId=setTimeout(syncFromCaret,150);});
ta.addEventListener('click',function(){clearTimeout(cId);cId=setTimeout(syncFromCaret,150);});
ta.addEventListener('input',function(){clearTimeout(tId);tId=setTimeout(refresh,400);});
ta.addEventListener('paste',function(e){
  var items=(e.clipboardData&&e.clipboardData.items)||[];
  for(var i=0;i<items.length;i++){
    if(items[i].type&&items[i].type.indexOf('image/')===0){
      e.preventDefault();addImage(items[i].getAsFile());return;
    }
  }
});
ta.addEventListener('dragover',function(e){e.preventDefault();ta.classList.add('drop');});
ta.addEventListener('dragleave',function(){ta.classList.remove('drop');});
ta.addEventListener('drop',function(e){
  e.preventDefault();ta.classList.remove('drop');
  var fs=(e.dataTransfer&&e.dataTransfer.files)||[];
  for(var i=0;i<fs.length;i++)addImage(fs[i]);
});
function saveDeck(deck){
  var blob=new Blob([deck],{type:'text/html'});
  var a=document.createElement('a');
  try{a.href=URL.createObjectURL(blob);}catch(e){return;}
  a.download=($('#fname').value||'deck.html').replace(/[^\w.\u4e00-\u9fff\-]+/g,'-');
  document.body.appendChild(a);a.click();a.remove();
  setTimeout(function(){URL.revokeObjectURL(a.href);},2000);
}
$('#dl').addEventListener('click',function(){
  var deck=buildDeck(ta.value);
  if($('#embM').checked){
    status.textContent=STR[LANG].embWork;
    _embedMath(deck).then(function(r){
      if(!r.ok)pendingMsgs.push(STR[LANG].embFail+r.why);
      saveDeck(r.deck);refresh();
    });
  }else saveDeck(deck);
});
$('#exp').addEventListener('click',function(){
  var name=(slug(parseOutline(ta.value).meta.title,{})||'talk')+'.outline.txt';
  var blob=new Blob([ta.value],{type:'text/plain'});
  var a=document.createElement('a');
  try{a.href=URL.createObjectURL(blob);}catch(e){return;}
  a.download=name;
  document.body.appendChild(a);a.click();a.remove();
  setTimeout(function(){URL.revokeObjectURL(a.href);},2000);
});
$('#thSel').addEventListener('change',function(){
  var v=this.value,lines=ta.value.split('\n'),done=false;
  var stop=lines.findIndex(function(l){return /^#\s/.test(l)||/^##\s/.test(l);});
  if(stop<0)stop=lines.length;
  for(var k=0;k<stop;k++){
    if(/^theme\s*:/i.test(lines[k])){
      if(v)lines[k]='theme: '+v;else lines.splice(k,1);
      done=true;break;
    }
  }
  if(!done&&v)lines.splice(stop,0,'theme: '+v);
  applyOutline(lines.join('\n'));
});
$('#imp').addEventListener('change',function(){
  var f=this.files[0];if(!f)return;
  var r=new FileReader();
  r.onload=function(){
    var o=extractOutline(r.result);
    if(o){
      var as=extractAssets(r.result),k;
      for(k in as)ASSETS[k]=as[k];
      ta.value=o;refresh();
    }
    else if(/\.txt$/i.test(f.name)||!/<html/i.test(r.result)){
      ta.value=r.result;refresh();  /* raw outline (H5) */
    }
    else alert(STR[LANG].noOutline);
  };
  r.readAsText(f);
});
ta.value=SAMPLE[LANG]||SAMPLE.en;
setLang(LANG);
$('#lang').addEventListener('click',function(){setLang(LANG==='en'?'zh':'en');});
window.buildDeck=buildDeck;
window.extractOutline=extractOutline;
window.extractAssets=extractAssets;
window.parseOutline=parseOutline;
window.setLang=setLang;
window.ASSETS=ASSETS;
window.fixSlide=fixSlide;
window._map=function(){return MAP.slice();};
window._lints=function(){return LINTS.map(function(x){return x.msg;});};
window._setFetch=function(f){doFetch=f;};
window._embedMath=_embedMath;
window._archive=archiveAll;
window._qrSvg=qrSvg;
window._caretIndex=caretIndex;
})();
</script>
</body>
</html>
"""

# safety pass: decode any \uXXXX that slipped into the raw template
COMPOSE = re.sub(r'\\u([0-9a-fA-F]{4})', lambda m: chr(int(m.group(1), 16)), COMPOSE)
assert '\\u' not in COMPOSE

out = (COMPOSE
       .replace('__QRLIB__', qrlib)
       .replace('__SHELL__', B64)
       .replace('__SAMPLE__', json.dumps({'en': SAMPLE_EN, 'zh': SAMPLE_ZH}, ensure_ascii=False))
       .replace('__BUILD__', re.search(r'Build (v[\d.]+)', deck).group(1)))
open('compose.html', 'w', encoding='utf-8').write(out)
print('compose.html:', out.count('\n') + 1, 'lines,', round(len(out.encode()) / 1024, 1), 'KB')
